#spring:
#
#  profiles:
#    active: local # default env
#
#  messages:
#    basename: i18n/exception
#    encoding: UTF-8
#
#  jwt:
#    secret: 1234

##################
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: 1234

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace